---
- name: clear history
  shell: cat /dev/null > ~/.bash_history && history -c
  args:
    executable: /bin/bash
  changed_when: false

- name: start openvpn
  service:
    name: "openvpn@{{ item.proto }}-{{ item.port }}.service"
    state: started
  with_items: "{{ openvpn_instances }}"
