---
- name: OpenVPN | package | Ensure the APT cache is up to date
  apt:
    update_cache: yes
  changed_when: False
  when: ansible_os_family == "Debian"

- name: OpenVPN | package | Install {{ ansible_os_family }} specific packages
  package:
    name: "{{ item }}"
  with_items: "{{ os_family_specific_pre }}"
  register: install_specific_result
  until: install_specific_result is success
  retries: 5
  delay: 5

- name: OpenVPN | package | Get official OpenVPN APT key
  # Work around for ansible issue https://github.com/ansible/ansible/issues/22647
  get_url:
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
    dest: ~/openvpn.gpg
  when: ansible_os_family == "Debian"

- name: OpenVPN | package | Add the official OpenVPN APT key
  # Work around for ansible issue https://github.com/ansible/ansible/issues/22647
  apt_key:
    file: ~/openvpn.gpg
    state: present
  when: ansible_os_family == "Debian"

- name: OpenVPN | package | Reread ansible_lsb facts
  setup: filter=ansible_lsb*

- name: OpenVPN | package | Add the official OpenVPN repository
  apt_repository:
    repo: 'deb https://build.openvpn.net/debian/openvpn/stable {{ ansible_lsb.codename }} main'
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: OpenVPN | package | Add debian backports
  apt_repository:
    repo: 'deb http://ftp.debian.org/debian {{ ansible_lsb.codename }}-backports main'
    state: present
    update_cache: yes
  when: ansible_distribution in ['Debian']

- name: OpenVPN | package | Upgrade systemd on debian
  apt:
    name: systemd
    state: latest
    default_release: "{{ ansible_lsb.codename }}-backports"
  when: ansible_distribution in ['Debian']
  tags:
    # Need latest, systemd v215 is really old and a pain to support alongside newer versions
    - skip_ansible_lint

- name: OpenVPN | package | Install required packages
  package:
    name: "{{ item }}"
  with_items: "{{ required_packages }}"
  register: install_required_result
  until: install_required_result is success
  retries: 5
  delay: 5
  tags:
    - skip_ansible_lint

- name: OpenVPN | package | Install pexpect via pip
  pip:
    name: "pexpect"
    version: "3.3"
